import React from "react";
import { Search, MoreVertical, Eye, Download, ChevronLeft, ChevronRight, FileText, Star } from "lucide-react";
import { reportsList, recentlyViewed, savedTemplates } from "./data";

function FormatBadge({ format }: { format: string }) {
  return (
    <span className={`text-[10px] font-bold px-2 py-0.5 rounded flex items-center gap-1 w-fit ${format === "PDF" ? "bg-red-100 text-red-600" : format === "XLSX" ? "bg-green-100 text-green-700" : "bg-blue-100 text-blue-700"}`}>
      <FileText className="w-2.5 h-2.5" /> {format}
    </span>
  );
}

export default function ReportsListSection() {
  return (
    <div className="grid grid-cols-3 gap-3">
      {/* Reports List */}
      <div className="col-span-2 bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden flex flex-col">
        <div className="p-3 border-b border-gray-100 flex items-center justify-between">
          <h3 className="text-xs font-bold text-gray-800">Reports List</h3>
          <div className="flex items-center gap-2">
            <div className="relative">
              <Search className="w-3 h-3 text-gray-400 absolute left-2 top-1/2 -translate-y-1/2" />
              <input placeholder="Search reports..." className="pl-6 pr-3 py-1.5 text-xs border border-gray-200 rounded-lg w-36 focus:outline-none" />
            </div>
            <button className="p-1.5 border border-gray-200 rounded-lg hover:bg-gray-50"><MoreVertical className="w-3.5 h-3.5 text-gray-400" /></button>
          </div>
        </div>
        <div className="overflow-x-auto flex-1">
          <table className="w-full text-xs">
            <thead>
              <tr className="border-b border-gray-100 text-[10px] text-gray-400 font-medium bg-gray-50/50">
                <th className="text-left px-3 py-2">Report Name</th>
                <th className="text-left px-3 py-2">Category</th>
                <th className="text-left px-3 py-2 text-center">Description</th>
                <th className="text-left px-3 py-2">Last Generated</th>
                <th className="text-left px-3 py-2">Generated By</th>
                <th className="text-left px-3 py-2">Format</th>
                <th className="px-3 py-2 text-right">Actions</th>
              </tr>
            </thead>
            <tbody>
              {reportsList.map((r, i) => (
                <tr key={i} className="border-b border-gray-50 hover:bg-gray-50 transition cursor-pointer">
                  <td className="px-3 py-2.5 font-semibold text-gray-800 text-[11px] whitespace-nowrap">{r.name}</td>
                  <td className="px-3 py-2.5">
                    <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${r.categoryColor}`}>{r.category}</span>
                  </td>
                  <td className="px-3 py-2.5 text-[10px] text-gray-500 max-w-[140px] truncate">{r.desc}</td>
                  <td className="px-3 py-2.5 text-[10px] text-gray-500 whitespace-nowrap">{r.lastGenerated}</td>
                  <td className="px-3 py-2.5 text-[10px] text-gray-600 font-medium">{r.by}</td>
                  <td className="px-3 py-2.5"><FormatBadge format={r.format} /></td>
                  <td className="px-3 py-2.5">
                    <div className="flex items-center gap-1 justify-end">
                      <button className="p-1 rounded hover:bg-gray-200"><Eye className="w-3.5 h-3.5 text-gray-400" /></button>
                      <button className="p-1 rounded hover:bg-gray-200"><Download className="w-3.5 h-3.5 text-gray-400" /></button>
                      <button className="p-1 rounded hover:bg-gray-200"><MoreVertical className="w-3.5 h-3.5 text-gray-400" /></button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="px-3 py-2 border-t border-gray-100 flex items-center justify-between">
          <span className="text-[10px] text-gray-400">Showing 1 to 8 of 24 reports</span>
          <div className="flex items-center gap-1">
            <button className="p-1 rounded border border-gray-200"><ChevronLeft className="w-3 h-3" /></button>
            {[1, 2, 3].map(n => <button key={n} className={`px-2 py-0.5 rounded border text-[10px] ${n === 1 ? "bg-indigo-600 text-white border-indigo-600" : "border-gray-200"}`}>{n}</button>)}
            <button className="p-1 rounded border border-gray-200"><ChevronRight className="w-3 h-3" /></button>
          </div>
        </div>
      </div>

      {/* Recently Viewed + Saved Templates */}
      <div className="flex flex-col gap-3">
        <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden flex flex-col">
          <div className="px-4 py-3 border-b border-gray-100 flex items-center justify-between">
            <h3 className="text-xs font-bold text-gray-800">Recently Viewed Reports</h3>
            <button className="text-[11px] text-indigo-600 hover:underline">View All</button>
          </div>
          <div className="flex flex-col divide-y divide-gray-50">
            {recentlyViewed.map((r, i) => (
              <div key={i} className="flex items-center gap-3 px-4 py-2.5 hover:bg-gray-50 transition cursor-pointer">
                <span className="text-lg">{r.icon}</span>
                <div className="flex-1 min-w-0">
                  <p className="text-[11px] font-semibold text-gray-800 truncate">{r.name}</p>
                  <p className="text-[10px] text-gray-400">{r.at} • {r.by}</p>
                </div>
                <ChevronRight className="w-3 h-3 text-gray-300 shrink-0" />
              </div>
            ))}
          </div>
        </div>

        <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden flex flex-col">
          <div className="px-4 py-3 border-b border-gray-100 flex items-center justify-between">
            <h3 className="text-xs font-bold text-gray-800">Saved Templates</h3>
            <button className="text-[11px] text-indigo-600 hover:underline">View All</button>
          </div>
          <div className="flex flex-col divide-y divide-gray-50">
            {savedTemplates.map((t, i) => (
              <div key={i} className="flex items-center gap-2 px-4 py-2.5 hover:bg-gray-50 transition cursor-pointer">
                <Star className="w-3.5 h-3.5 text-amber-400 fill-amber-400 shrink-0" />
                <div className="flex-1 min-w-0">
                  <p className="text-[11px] font-semibold text-gray-800 truncate">{t.name}</p>
                  <p className="text-[10px] text-gray-400 truncate">{t.tags}</p>
                </div>
                <MoreVertical className="w-3 h-3 text-gray-300 shrink-0" />
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
